twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 90
      keyboard:
        topic: key_vel
        timeout: 0.5
        priority: 100
